[complexity]
low_threshold = 15
medium_threshold = 25

[dead_code]
min_severity = "warning"

[clones]
min_lines = 15                   # Require at least 15 lines for duplication detection (exclude small logging boilerplate)
min_nodes = 25                   # Require at least 25 AST nodes (exclude simple patterns)
similarity_threshold = 0.85      # Require 85% similarity (focus on true duplicates)

[output]
directory = ".pyscn/reports"

[analysis]
recursive = true                 # Recursively analyze directories
follow_symlinks = false          # Follow symbolic links
include_patterns = ["**/*.py"]   # File patterns to include
exclude_patterns = [             # File patterns to exclude
    ".env/",
    ".tox/",
    ".venv/",
    "**/__pycache__/*",
    "**/.pytest_cache/",
    "**/*.pyc",
    "**/tests/**",
    "api/examples/**",           # Exclude API example/automation code
    "env/",
    "utils/*",
    "venv/",
    "scratch.py",
]
