version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  TLD: "{{.ROOT_DIR}}"
  VENV_DIR: "{{.ROOT_DIR}}/.venv"
  PATH: "{{.VENV_DIR}}/bin:{{.PATH}}"

vars:

includes:
  uv:
    taskfile: ./taskfiles/uv.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install-devbox:
    desc: "Install devbox"
    cmds:
      - curl -fsSL https://get.jetify.com/devbox | bash
    run: once
    silent: true
    environment:
      FORCE: 1
      INSTALL_DIR: "{{.HOME}}/.local/bin"
    status:
      - command -v devbox 2>/dev/null

  install:
    desc: "Install project dependencies"
    deps: ["install-devbox"]
    cmds:
      - devbox install

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  lint:
    desc: "Run linters"
    cmds:
      - ruff check --fix --respect-gitignore

  format:
    desc: "Run formatters"
    cmds:
      - ruff format --respect-gitignore

  test:
    desc: "Run tests"
    cmds:
      - pytest

  pyclean:
    desc: "Remove .pyc and __pycache__"
    cmds:
      - |
        args=(
          .
          --debris
          --verbose
          -i .devbox
        )
        case "{{.CLI_ARGS}}" in
          dry-run)
            pyclean "${args[@]}" --dry-run
            ;;
          *)
            pyclean "${args[@]}"
            ;;
        esac

  repomix:
    desc: "Create llm snapshot of repo"
    preconditions:
      - sh: command -v repomix 2>/dev/null
        msg: "repomix is not installed. Install with: npm install -g repomix"
    cmds:
      - |
        repomix \
          --style markdown \
          --compress \
          --remove-comments \
          --remove-empty-lines \
          --truncate-base64
    sources:
      - "**/*.py"
      - "**/*.zig"
      - "**/*.toml"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.md"
      - "**/*.json"
      - ".repomix*"
    generates:
      - repomix-output.md
