version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

vars:

includes:
  npm:
    taskfile: ./taskfiles/npm.yml
  tauri:
    taskfile: ./taskfiles/tauri.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install-devbox:
    desc: "Install devbox"
    cmds:
      - curl -fsSL https://get.jetify.com/devbox | bash
    run: once
    silent: true
    environment:
      FORCE: 1
      INSTALL_DIR: "{{.HOME}}/.local/bin"
    status:
      - command -v devbox 2>/dev/null

  install:
    desc: "Install project dependencies"
    deps: ["install-devbox"]
    cmds:
      - devbox install

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  lint:
    desc: "Run linters"
    cmds:
      - cargo clippy --manifest-path src-tauri/Cargo.toml
      - deno lint

  format:
    desc: "Run formatters"
    cmds:
      - cargo fmt --manifest-path src-tauri/Cargo.toml
      - deno fmt

  test:
    desc: "Run tests"
    cmds:
      - cargo test --manifest-path src-tauri/Cargo.toml
      - npm --prefix app/frontend test

  test:e2e:
    desc: "Run Playwright E2E tests"
    cmds:
      - npm --prefix app/frontend run test:e2e

  build:
    desc: "Build Tauri app for current architecture"
    cmds:
      - task: tauri:build

  build:arm64:
    desc: "Build Tauri app for Apple Silicon (arm64)"
    cmds:
      - task: tauri:build:arm64

  build:x64:
    desc: "Build Tauri app for Intel (x86_64)"
    cmds:
      - task: tauri:build:x64

  repomix:
    desc: "Create llm snapshot of repo"
    preconditions:
      - sh: command -v repomix 2>/dev/null
        msg: "repomix is not installed. Install with: npm install -g repomix"
    cmds:
      - |
        repomix \
          --style markdown \
          --compress \
          --remove-comments \
          --remove-empty-lines \
          --truncate-base64
    sources:
      - "**/*.rs"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.toml"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.md"
      - "**/*.json"
      - ".repomix*"
    generates:
      - repomix-output.md
